# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pantry_tracker_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=563565
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Strategy
# 'update' automatically maps your @Entity classes to these SQL tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Jackson settings to match your frontend ISO date strings
# spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false